docs/treeherder.md
As far as I can see in the code and in the deployed stuff, we have the pattern:
`<prefix>.<project>.<revision_hash>`
=> Route should be: prefix.project.revision_hash

src/config.js, src/config/default.yml, src/config/production.yml, src/jobs/treeherder_resultset.js
This allows staging environment to handle all task graph creation for
now so we don't end up running twice the work for no reason.
=> Add on/off switch for try logic

src/config/default.yml
I'm working on getting some Buildbot jobs into the task graph in https://bugzilla.mozilla.org/show_bug.cgi?id=1157242, so I'll need to get taskcluster-graph to start running on Alder to test/verify my work.
=> Enable Taskcluster jobs on Alder for bug 1157242.

src/config/production.yml, src/config/stage.yml
This will allow mozilla-taskcluster to use production treeherder rather than staging.
=> Production should create task graphs and not rely on staging

src/config.js, src/config/default.yml, src/project_scopes.js, test/project_scopes_test.js
This shifts mozilla-taskcluster to use roles named
`moz-tree:{{{alias}}}` for each tree (aka project aka alias) instead of
hard-coding the tree's scopes.
=> Bug 1216306: use roles for trees

src/bin/create_graph.js, src/jobs/retrigger.js, src/jobs/taskcluster_graph.js, src/jobs/treeherder_resultset.js
Just a start with getting some useful things in the logs.  It appears that "job.log" wasn't actually getting captured in the logs.  Just made it a straight forward console.log() call like everywhere else.
=> Include project in logging statements

src/jobs/treeherder_resultset.js, src/treeherder/job_handler.js
Prior to switching to use hawk authentication, there were per project
credentials for treeherder.  This credentials list contained many repos
that by default were getting things pushed to treeherder.  Once
switching over to hawk and no longer having this credentails list,
projects that were once submitting to treeherder are no longer working.
This should allow this to continue on since posting to treeherder does
not require any special privileges from a taskcluster perspective.
=> Create project instance if one does not exist

src/jobs/retrigger.js, src/jobs/taskcluster_graph.js
Untested, but should be safe enough to land and see what happens when I delete the `repo:*` role.
=> Bug 1220298: include scheduler:create-task-graph in authorizedScopes

src/config/default.yml, src/jobs/taskcluster_graph.js, src/project_scopes.js
I'll then add `--level {{level}}` to the decision tasks, make that a YAML template variable, and then use cache names like `level-{{level}}-{{project}}-tc-vcs`.
=> Bug 1220684: supply SCM level to decision tasks; r?garndt

src/jobs/retrigger.js, src/treeherder/action_handler.js, src/treeherder/job_handler.js
Retriggers are an async operation and if creating the new task graph fails, nothing indicates this within TH for the user to see.
This change will allow an error job be posted to TH that will appear as an exception with an error indicating that the retrigger could not be completed.
Job where this can be seen: 
https://treeherder.allizom.org/#/jobs?repo=mozilla-central&selectedJob=2953881
=> Bug 1242675 - Post to treeherder when retrigger failed

src/treeherder/job_handler.js
This is the same list that's found in the option ordering in Treeherder's UI.  This wouldn't have stopped an option of 'asan' from being submitted because unknown(true), but at least now that they're list they'll be validated.
=> Update option collection types to match treeherder

src/config/default.yml, src/jobs/taskcluster_graph.js, src/project_scopes.js
With this change, if a repo has a `.taskcluster.yml`, it will be used to
run the decision task instead of `testing/taskcluster/tasks/decision/<whatever>.yml`.
This should allow a gradual transition as `.taskcluster.yml` is merged around.
=> Bug 1274391: try `.taskcluster.yml` first

npm-shrinkwrap.json, package.json, src/jobs/retrigger.js, src/taskcluster/duplicate_task.js, src/taskcluster/duplicator.js, test/jobs/retrigger_test.js, test/taskcluster/duplicator_test.js
* upgrade to tc-client@1.0.1 to get the new queue methods
* factor subgraph duplication out and implement it for big-graph scheduler
* use subgraph duplication for retriggering tasks in big-graph groups
* tests!
When duplicating in a group, this keeps the new tasks in the same group as the old, and adjusts intra-subgraph dependencies appropriately while maintaining dependencies pointing out of the subgraph.
The new tests do, in fact, pass, and helped track down a number of subtle bugs (some of which also exist in the old task-graph duplicator).  I haven't run this in any kind of staging environment, though, so if you have suggestions for ways I might test that, I'm all ears.
=> Bug 1274176: support duplicating subgraphs of big graphs

src/jobs/retrigger.js, test/jobs/retrigger_test.js
This should fix up an issue where tasks within a retriggered portion of a graph did not have the old task IDs replaced within the task definition.
=> Retriggering tasks should replace old task Ids in definitions

src/jobs/retrigger.js, test/jobs/retrigger_test.js
When recursing over the group of tasks, ensure that the old task id is
not replaced while doing so.
=> Ensure old task IDs are preserved

src/jobs/taskcluster_graph.js
`npm test` didn't tell me much, but this is pretty durn simple.  The `push.date` is based on [this example](https://hg.mozilla.org/build/puppet/json-pushes?startID=3000&endID=3001&version=2) where `date` is a peer property to `changesets`.
=> Bug 1286075: pass pushdate to decision task

src/treeherder/action_handler.js
This is to limit the out of control effect when retriggering for some reasons fails at some point in the process.  Before when things were scheduled through the scheduler it was better, but now that each task has it's own createTask event on the queue, somewhere in there things could fail, causing some tasks to be created and another retrigger attempted.
=> Only attempt to retrigger one time

package.json, src/jobs/taskcluster_graph.js
This would be used like this:
```
--message={{#shellquote}}{{{comment}}}{/shellquote}}
```
Aside from deploying to staging, I don't have a good idea of how to test this..
=> Bug 1252235: add a shellquote filter

src/config/default.yml
I'm not sure of the scopes, or if there should be a single role that implies the rest (or where to create it).
This will also need a entry created in the config db for the equivalent of https://github.com/taskcluster/mozilla-taskcluster/blob/master/src/bin/import_repositories.js
=> Bug 1380704 - Add project for thunderbird experimentation and migration.

src/jobs/taskcluster_graph.js
This will allow continued building of older decision tasks and branches.
=> Bug 1437562 - massage the scopes for decision tasks

src/config.js, src/config/default.yml, src/config/production.yml, src/config/stage.yml, test/config_test.js
In (to mozilla-taskcluster) for a penny, in for a pound..
This is still pulling from the old https://hg.mozilla.org/build/tools/raw-file/default/buildfarm/maintenance/production-branches.json, which is no longer being updated.
=> Bug 1437563 - read from projects.yml

src/config.js, src/config/default.yml, src/config/test.yml, src/runtime.js, src/treeherder/action_handler.js
This is the smallest change I could make. Anything more than this and my head started to hurt.
It should end up passing in exactly what is in mongo currently.
Tests? What are tests? I don't know that anyone has known exactly how to run these tests in a long time.
https://bugzilla.mozilla.org/show_bug.cgi?id=1465606
=> Don't store redis config in mongo

src/config.js, test/config_test.js
@jhford: Just requesting you for review since you javascript. The bug contains background info.
This feels like a safer middleground before accepting `scm_*` which we can talk more about once @djmitche is back?
=> Bug 1469049 - Accept versioncontroltools

src/config.js
The stuff we removed in https://github.com/taskcluster/mozilla-taskcluster/pull/133 set this level to 3, so we never noticed this bit of missing support..
=> Bug 1501306 - handle scm_nss as level 3

src/config.js, src/config/production.yml, src/config/stage.yml, test/config_test.js
This needs to be deployed after the move [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1525368) takes place.
=> Bug 1525368: Update path to ci-config.
