taskcluster/mozilla-taskcluster

package.json, src/jobs/retrigger.js, src/jobs/taskcluster_graph.js, src/try/instantiate.js, test/jobs/taskcluster_graph_test.js, test/setup.js, test/taskcluster.js, test/treeherder/action_handler_test.js, test/treeherder/job_handler_test.js, test/try/instantiate_test.js
@garnt Feel free to throw to someone else if you are too busy.
=> Bug 1194767 - use 'nice' slugs in mozilla-taskcluster

src/config/default.yml
Updated default.yml with the definition for pine.
=> added pine to default.yml

package.json
Will this cause issues with deployment?
=> Fix package name and metadata

src/config.js, src/config/default.yml, src/project_scopes.js, test/project_scopes_test.js
Reverts taskcluster/mozilla-taskcluster#30
=> Revert "Bug 1216306: use roles for trees"

src/config/default.yml
Please don't deploy this until we have the repos ready.
=> Bug 1218059 - Need taskcluster build for 2.5 branch

src/config.js, src/config/default.yml, src/jobs/retrigger.js, src/project_scopes.js, test/project_scopes_test.js
Compared to last time, this uses roles more like those from gaia-taskcluster.
=> Bug 1216306: switch to using roles per tree

src/jobs/taskcluster_graph.js, src/try/instantiate.js
Validation was failing when instantiating the decision task because level was not added to another spot where things are validated (I didn't realize how many places Joi is used).
=> Add Level to template parameter validation

npm-shrinkwrap.json
Just the results of running `npm shrinkwrap` after `npm install`.
=> Add npm shrinkwrap

src/config/default.yml
Removing b2g-inbound. 
Not sure this is all that needs to be done for this change for taskcluster.. but hoping :)
=> [bug 1265799] Disable b2g-inbound

src/config/default.yml
Removing cedar from default.yml
=> Bug 1272005 - Disable cedar branch

src/treeherder/job_handler.js
=> Detect if task is part of graph vs group

src/config/default.yml
Adding entries for autoland repo
=> Bug 1267712 - Enable build automation on the autoland repo

src/config/default.yml, src/jobs/taskcluster_graph.js
TOTALLY UNTESTED!  What do you think?
=> add per-repo scopes to decision tasks

src/jobs/retrigger.js
This should maintain existing behavior with rescheduling nodes within a task graph, but also allow an individual task to be retriggered within a task *group*
=> Bug 1274176 - Retrigger big-graph scheduler task

package.json, src/jobs/taskcluster_graph.js, src/try/instantiate.js
Per discussion in #85.  This is, sadly, untested.  I think this can wait until greg returns to land, so I've flagged him for review.
=> (updated) Schedule decision task using big graph scheduler

src/try/instantiate.js
=> Bug 1291473: actually substitute pushdate; r?garndt

src/config/default.yml
Pretty self-explanatory change. The "stylo" repo is level 2.
The "stylo-try" repo is level 1.
=> Bug 1297817 - Enable build automation on the stylo repos

src/jobs/taskcluster_graph.js, src/try/instantiate.js
This moves the handling to instantiate, and fixes the error handling for the instantiation.
=> Bug 1252235: better handling of shell quoting 

.gitignore, src/jobs/taskcluster_graph.js, src/project_scopes.js
I'm not 100% (or even 50%) sure that this is the right way to do this, but in conjunction with the in-tree changes for https://bugzilla.mozilla.org/show_bug.cgi?id=1275774, I think this will work?
Please tell me to go back to the drawing board if this isn't correct, I have no attachment to this particular diff!
Related: https://reviewboard.mozilla.org/r/80590/
=> Add a scope to allow users to email themselves

src/jobs/retrigger.js
=> Add scope for retrigger (bug 1308543)

src/config/default.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1321043
=> Make date an L3 repo

src/config/default.yml
=> Bug 1382294: remove legacy assume:repo:hg.mozilla.org/try:*

package.json
Fix fromNow to always be the same timestamp even if rendering takes a little time...
=> Bump json-e version

package.json
In particular, this achieves sorted $json renders.
=> Upgrade JSON-e to 2.5.0

src/config/default.yml
@djmitche Note the comment about removing the database entry associated with `comm-taskcluster`.
=> Remove old repos
